### PR TITLE
mark CAtomic import as internal or implementation-only

### LINKED ISSUE #195: Cannot use `swift-markdown` in package built for distribution
I've created an incredibly simple [package](https://github.com/user-attachments/files/16789717/MyLibrary.zip) with `swift-markdown` as the only dependency.

Archiving my package for distribution with the following command fails:

`xcodebuild archive -scheme MyLibrary -destination generic/platform=iOS -archivePath /Users/[username]/Desktop/iOS.xcarchive BUILD_LIBRARY_FOR_DISTRIBUTION=YES`

```
/Users/[username]/Library/Developer/Xcode/DerivedData/MyLibrary-guqxdcvdzivakeakwqoytmpxwgur/Build/Intermediates.noindex/ArchiveIntermediates/MyLibrary/IntermediateBuildFilesPath/swift-markdown.build/Release-iphoneos/Markdown.build/Objects-normal/arm64/Markdown.private.swiftinterface:4:8: error: no such module 'CAtomic'
import CAtomic
       ^
/Users/[username]/Library/Developer/Xcode/DerivedData/MyLibrary-guqxdcvdzivakeakwqoytmpxwgur/Build/Intermediates.noindex/ArchiveIntermediates/MyLibrary/IntermediateBuildFilesPath/swift-markdown.build/Release-iphoneos/Markdown.build/Objects-normal/arm64/Markdown.private.swiftinterface:1:1: error: failed to verify module interface of 'Markdown' due to the errors above; the textual interface may be broken by project issues or a compiler bug
// swift-interface-format-version: 1.0
^

** ARCHIVE FAILED **
```

Removing `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` succeeds
```
** ARCHIVE SUCCEEDED **
```

- swift-tools-version: 5.10
- Xcode + CLI Tools Version 15.4 (15F31d)

- Also reported as Apple Feedback FB14954614
- [Post](https://forums.swift.org/t/cannot-use-swift-markdown-in-package-built-for-distribution/74243) on forums.swift.org

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Bug/issue #, if applicable: fixes rdar://134894555, fixes #195

## Summary

The CAtomic target defined in this package is causing issues when verifying module interfaces of projects that depend on Swift-Markdown. This PR marks the import of CAtomic in Swift-Markdown as `internal` or `@_implementationOnly`, depending on the compiler in use, to sidestep the issue.

## Dependencies

None

## Testing

Ensure that no behavior has changed.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ n/a ] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ n/a ] Updated documentation if necessary

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by Kyle-Ye — APPROVED** [review]
LGTM. But IIRC `internal import` need something like `.enableExperimentalFeature("AccessLevelOnImport")` for Swift 5.10 compiler.

**Comment by Kyle-Ye** [comment]
Confirmed it. [SE409](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md) stated that only main and release/5.9 needed this flag, but it is actually also needed for 5.10 compiler.

Tested with Xcode 15.3 + Swift 5.10

image

File: Sources/Markdown/Utility/AtomicCounter.swift [hunk 1]
```diff
@@ -8,7 +8,11 @@
  See https://swift.org/CONTRIBUTORS.txt for Swift project authors
 */
 
-import CAtomic
+#if compiler(>=5.10)
```
Comment (Kyle-Ye) [inline Sources/Markdown/Utility/AtomicCounter.swift:11]:
```suggestion
#if compiler(>=6.0)
```

Comment (Kyle-Ye) [inline Sources/Markdown/Utility/AtomicCounter.swift:11]:
```suggestion
#if compiler(>=6.0)
```

**Review by Kyle-Ye — CHANGES_REQUESTED** [review]

File: Sources/Markdown/Utility/AtomicCounter.swift (hunk 1 above)
Comment (QuietMisdreavus) [reply Sources/Markdown/Utility/AtomicCounter.swift]: Thanks so much! I wasn't sure if it was fine, so thanks for verifying.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by Kyle-Ye — APPROVED** [review]
